repos:
  # - repo: https://github.com/cisagov/pre-commit-packer
  #   rev: v0.0.2
  #   hooks:
  #     - id: packer_validate
  #     - id: packer_fmt
  #       args: ["-recursive"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=./.yamllint]
